version: "3"
services:
  mysql_db:
    image: mysql:5.7
    container_name: db_mysql_server
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gains_db
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=localhost
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  # nginx:
  #   depends_on:
  #     - api
  #   restart: always
  #   container_name: bbsl_nginx
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./docker-compose/nginx
  #   ports:
  #     - "5000:80"
